model: 'DisNet'

## parameters for plain
scale: 4
rgb_range: 255
colors: 3
Module2_depth: 24
channels: 64
r_expand: 2
window_sizes: [4, 8, 16]

## parameters for model training
patch_size: 256
batch_size: 16
data_repeat: 80
data_augment: 1

epochs: 1000
lr: 0.0002
decays: [50, 100, 120, 150, 200]
gamma: 0.5

## hardware specification
gpu_ids: [0]
threads: 8

## data specification
# data_path: '/opt/data/private/ELAN_total/SR_datasets'
data_path: 'E:/SR_datasets'
# eval_sets: ['Set5', 'Set14', 'B100', 'Urban100', 'Manga109']
eval_sets: ['Set5', 'Set14', 'B100']
# eval_sets: ['Set5']